---
- name: Deploy and configure Docker
  hosts: remoteserver
  tasks:
   - name: Configuring Docker Repository
     command: sudo yum update -y
       #yum install -y yum-utils device-mapper-persistent-data lvm2
       #yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     #yum_repository:
     #name: Docker
     #description: "Docker Repo"
     #baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/Packages/"
     #gpgcheck: no
     #enabled: 1
     register: x

   - name: Checking Configuration Status
     debug:
       var: x.failed

   - name: Installing Docker
     command: sudo yum install docker -y
       #package:
       #name: "docker-ce-18.06.3.ce-3.el7.x86_64"
       #state: present
     register: y

   - name: Checking Install Status
     debug:
       var: y.failed

   - name: Starting Docker Daemon
     command: sudo systemctl start docker
             #sudo systemctl enable docker
       #service:
       #name: docker
       #state: started
       #enabled: yes
     when: y.failed == false

   - name: Install python package
     command: sudo pip3 install docker-py

   - name: stop existing container
     command: docker stop apache-server
     ignore_errors: yes

   - name: remove the container
     command: docker rm apache-server
     ignore_errors: yes

       #- name: remove image
       #command: docker rmi httpd
       #ignore_errors: yes

   - name: Pull a Docker Image
     command: sudo docker pull httpd:latest
       #docker_image:
       #name: httpd
       #tag: latest
       #source: pull
     register: z

   - name: Checking Pull Status
     debug:
       var: z

   - name: Creating a Persistent Volume Dir
     file:
       path: "/root/pv"
       state: directory

   - name: Copying the HTML code in the Directory
     copy: 
       src: "/var/www/html/index.html"
       dest: "/root/pv"

   - name: Launching an HTTPD Container
     when: z.failed == false
     command: sudo docker run -it --name apache-server -p 8082:80 httpd 
      #docker_container:
            #name: apache-server
            #image: httpd
            #state: started
            #exposed_ports:
            #-"80"
            #ports:
            #-"8888:80"
