---
- hosts: docker
  tasks:
   - name: Configuring Docker Repository
     yum_repository:
       name: Docker
       description: "Docker Repo"
       baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/Packages/"
       gpgcheck: no
       enabled: 1
     register: x
     
   - name: Checking Configuration Status
     debug:
       var: x.failed
       
   - name: Installing Docker
     #command: yum install docker-ce -y
     package:
       name: "docker-ce-18.06.3.ce-3.el7.x86_64"
       state: present
     register: y
     
   - name: Checking Install Status
     debug:
       var: y.failed
       
   - name: Starting Docker Daemon
     #command: systemctl start docker
     service:
       name: docker
       state: started
       enabled: yes
     when: y.failed == false
     
   - name: Install
     command: "pip install docker-py"
     
   - name: Pull a Docker Image
     #command: docker pull httpd:latest
     docker_image:
        name: httpd
        tag: latest
        source: pull
     register: z
     
   - name: Checking Pull Status
     debug:
       var: z
       
   - name: Launching an HTTPD Container
     when: z.failed == false
     #command: |
            #yum install httpd -y
            #docker run -it --name apache-server httpd -p 8888:80 -v /root/pv:/usr/local/apache2/htdocs
     docker_container:
       name: apache-server
       image: httpd
       state: started
       exposed_ports:
         - "80"
       ports:
         - "8888:80"
      
