name: Deploy and Configure Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Install Ansible
      run: |
        sudo apt-add-repository -y ppa:ansible/ansible
        sudo apt-get update
        sudo apt-get install -y ansible
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Configure SSH for remote VM
      run: |
        ssh-keyscan -H 54.172.247.135 >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
    - name: Run Ansible playbook
      run: ansible-playbook -i 54.172.247.135, playbook.yml --private-key ~/.ssh/id_rsa
