name: Configure and Deploy docker to Remote Host
on:
  push:
    branches:
      - master
env:
  HOST: 54.167.86.246
  USER: root

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: SSH keys
      uses: tanmancan/action-setup-ssh-agent-key@1.0.0 
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-public-key: ${{ secrets.SSH_PUBLIC_KEY }}
        ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Connect over SSH
      run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=~/.ssh/known_hosts -T ${{ env.USER }}@${{ env.HOST }}

    - name: Run Ansible Playbook
      run: ansible-playbook -i inventory.yml playbook.yml --extra-vars "ansible_connection=ssh ansible_user=${{ env.USER }} ansible_host=${{ env.HOST }} host_key_checking=false"
    
    - name: Deploy web application on container
      run: curl -v -T index.html 'http://ec2-54-167-86-246.compute-1.amazonaws.com:8082'


