name: Deploy to Remote Host
on:
  push:
    branches:
      - master
env:
  ANSIBLE_HOST: 172.31.62.26
  ANSIBLE_USER: ansadmin
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
        #- name: Configure SSH key
        #uses: tanmancan/action-setup-ssh-agent-key@1.0.0
      #with:
      #ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #ssh-public-key: ${{ secrets.SSH_PUBLIC_KEY }}
        #ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          #host: ${{ secrets.HOST }}
          #username: ${{ secrets.USERNAME }}
          #password: ${{ secrets.PASSWORD }}
    - name: Run Ansible Playbook
      #uses: euclid1990/actions-ansible@v2
      #with:
      #playbook: playbook.yml
          #inventory: |
          #[remote_server]
          #172.31.62.72
          #[ansible]
          #172.31.19.79
      run: ansible-playbook -i inventory.yml playbook.yml 
        #--extra-vars "ansible_connection=ssh ansible_user=${{ env.ANSIBLE_USER }} ansible_host=${{ env.ANSIBLE_HOST }}"


